[package]
name = "testrust"
version = "0.1.0"
authors = ["monkey <58288531+bencong55@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
